### ISSUE TITLE
V1.20 crashes when starting audio output

### ISSUE THREAD

**Issue by Fastsquirrel** [diglet48/restim#14]
V1.20 crashes when starting audio output, or using Test This Device option.

Line 93 of qt_ui/audio_generation_widget.py still references TCODE_LATENCY which was removed in commit 579b29f

```
INFO:restim.audio:Selected audio device: MME, Microsoft Sound Mapper - Output, high, 44100.0
INFO:restim.audio:attempting to open audio device with 2 channels.
CRITICAL:restim:Exception occurred
Traceback (most recent call last):
  File "qt_ui\audio_test_dialog.py", line 38, in audio_start_stop
  File "qt_ui\audio_test_dialog.py", line 50, in audio_start
  File "qt_ui\audio_generation_widget.py", line 93, in start
NameError: name 'TCODE_LATENCY' is not defined
INFO:restim.main:funscript mapping changed, re-linking scripts.
```

**Comment by diglet48** [comment]
Thanks. Fixed in v1.20.1
