### ISSUE TITLE
Funscript Conversion failed

### ISSUE THREAD

**Issue by 47dahc** [diglet48/restim#9]
With latest version, I get this error when trying to convert 1d to 2d.

Traceback (most recent call last):
  File "qt_ui\funscript_conversion_dialog.py", line 44, in convert
  File "funscript\funscript.py", line 45, in from_file
  File "funscript\funscript.py", line 20, in sha1_hash
AttributeError: 'str' object has no attribute 'open'

Converted just fine with previous versions and same funscript.

**Comment by diglet48** [comment]
Fixed, next release will contain the fix.

**Comment by diglet48** [comment]
Fixed in v1.16
